language: ruby

dist: trusty

script: npm i && JEKYLL_ENV=production bundle exec jekyll build

# branch whitelist, only for GitHub Pages
branches:
  only: develop

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false

deploy:
  provider: pages
  keep_history: true
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: master
  local-dir: _site
  on:
    branch: develop

cache:
  bundler: true
  directories:
  - /home/travis/.rvm/
  - node_modules
  - vendor/bundle
