title: "Esteemed.io"
description: "Scale your business with speed and confidence with trusted colleagues from the Esteemed Talent Network. Made up of over 13,000 digital professionals. The first and only integrated staffing and collaboration solution delivered through your existing communications platforms."
url: "https://esteemed.io"
email: service@esteemed.io
meta:
  image: "/img/main-hero.svg"
google_analytics: UA-167435008-1
twitter:
  username: EsteemedTalent
facebook:
  publisher: Esteemed-106526290944059
logo: /img/esteemed-bw-logo.svg
social:
  links:
    - https://www.facebook.com/Esteemed-106526290944059/
    - https://twitter.com/EsteemedTalent
    - https://www.linkedin.com/company/esteemed/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-menus
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap
author_dir: "blog/author"
author_title_suffix: ""
pagination:
  enabled: true
  per_page: 10
  permalink: "/:num/"
  title: ":title - page :num"
  limit: 0
  sort_field: "date"
  sort_reverse: true
autopages:
  enabled: true
  title: ':cat Posts'
  categories:
    layouts:
      - 'categories.html'
    permalink: "/blog/category/:cat/"
  collections:
    enabled: false
  tags:
    enabled: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      image: "/img/main-esteemed.png"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:year/:month/:day/:title/
      image: "/img/default-blog.jpg"
